/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#c6c6c6",
        "surface-tint": "#5e5e5e",
        "on-primary-fixed": "#1b1b1b",
        "tertiary": "#000000",
        "tertiary-fixed": "#e2e2e2",
        "outline-variant": "#cfc4c5",
        "surface-container-highest": "#e2e2e2",
        "surface-variant": "#e2e2e2",
        "on-primary-fixed-variant": "#474747",
        "on-error-container": "#93000a",
        "primary-fixed": "#e2e2e2",
        "secondary-fixed": "#e4e2e2",
        "surface-dim": "#dadada",
        "outline": "#7e7576",
        "on-background": "#1a1c1c",
        "surface-container": "#eeeeee",
        "tertiary-container": "#1b1b1b",
        "on-tertiary-fixed-variant": "#474747",
        "on-tertiary-container": "#848484",
        "secondary-container": "#e1dfdf",
        "on-surface": "#1a1c1c",
        "secondary": "#5e5e5e",
        "surface-bright": "#f9f9f9",
        "surface-container-high": "#e8e8e8",
        "on-tertiary-fixed": "#1b1b1b",
        "surface": "#f9f9f9",
        "inverse-primary": "#c6c6c6",
        "background": "#f9f9f9",
        "inverse-on-surface": "#f1f1f1",
        "on-secondary-fixed": "#1b1c1c",
        "surface-container-low": "#f3f3f3",
        "on-secondary-container": "#626262",
        "error-container": "#ffdad6",
        "error": "#ba1a1a",
        "surface-container-lowest": "#ffffff",
        "on-primary": "#ffffff",
        "on-primary-container": "#848484",
        "primary-container": "#1b1b1b",
        "inverse-surface": "#2f3131",
        "on-error": "#ffffff",
        "primary-fixed-dim": "#c6c6c6",
        "secondary-fixed-dim": "#c7c6c6",
        "on-tertiary": "#ffffff",
        "on-secondary": "#ffffff",
        "on-surface-variant": "#4c4546",
        "on-secondary-fixed-variant": "#464747",
        "primary": "#000000",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "stack-md": "24px",
        "margin-page": "10vw",
        "stack-sm": "12px",
        "section-padding": "80px",
        "gutter-linear": "120px",
        "stack-lg": "48px",
      },
      fontFamily: {
        "headline-lg-mobile": ["Playfair Display"],
        "label-caps": ["Inter"],
        "headline-lg": ["Playfair Display"],
        "section-header": ["Playfair Display"],
        "body-lg": ["Inter"],
        "body-md": ["Inter"],
        "display-xl": ["Playfair Display"],
        "mono-code": ["Courier Prime"],
      },
      fontSize: {
        "headline-lg-mobile": ["36px", { lineHeight: "44px", fontWeight: "600" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "600" }],
        "headline-lg": ["48px", { lineHeight: "56px", fontWeight: "600" }],
        "section-header": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "32px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-xl": ["72px", { lineHeight: "80px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "mono-code": ["14px", { lineHeight: "20px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
